
project_id = "djbdylsdanytgrdqhpzo"

[functions.ai-chat-assistant]
verify_jwt = true

[functions.voice-to-text]
verify_jwt = true

# Enable email confirmation to prevent multiple logins without verification
[auth]
disable_signup = false
enable_confirmations = true
