
project_id = "djbdylsdanytgrdqhpzo"

[functions.ai-chat-assistant]
verify_jwt = true

[functions.voice-to-text]
verify_jwt = true

# Disable email confirmation to make demo login easier
[auth]
disable_signup = false
enable_confirmations = false

