
project_id = "djbdylsdanytgrdqhpzo"

[functions.ai-chat-assistant]
verify_jwt = true

[functions.voice-to-text]
verify_jwt = true

# Email confirmation is enabled for security
[auth]
disable_signup = false
enable_confirmations = true
