
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djbdylsdanytgrdqhpzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqYmR5bHNkYW55dGdyZHFocHpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5OTU3NzIsImV4cCI6MjA2MTU3MTc3Mn0.2KUS7E5P_OJgjVvdTgSQYREWvBElcFirmxG29ZX7cSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
